### ISSUE TITLE
case_limit

### ISSUE THREAD

**Issue by joerg-d** [parallaxinc/OpenSpin#5]
For some of my projects I need a higher case_limit (e.g. 256). Is there any reason to set this to 64?

**Comment by konimaru** [comment]
So this means the case limit still applies (64)? Just seemed odd that the limit was increased and then removed again (according to the log messages).

**Comment by reltham** [comment]
No, I had submitted a partial set of files, reverted that, and then submitted the full set of files. The partial set of files didn't have a summary description while the full set did, this may have caused your confusion?  Just click the ... buttons to see the full description of the submits to see that the 3rd one also has the case_limit change to 256 in it.

**Comment by konimaru** [comment]
OK. It's Monday morning here before my first coffee. I'll check later. Thanks.

**Comment by konimaru** [comment]
Can you do something about the build errors (simple **make** invocation)?
```
g++ -Wall -g -static -o UnusedMethodUtils.o -c UnusedMethodUtils.cpp
UnusedMethodUtils.cpp: In function ‘int ScanLowerOpcode(unsigned char*, MethodUsage*, ObjectEntry*, unsigned char*)’:
UnusedMethodUtils.cpp:554:139: error: cast from ‘unsigned char*’ to ‘unsigned int’ loses precision [-fpermissive]
                 pUsage->pCalls[pUsage->nCurrCall].objaddress = (unsigned int)&pObject->pObject[pUsage->pCalls[pUsage->nCurrCall].objoffset];
                                                                                                                                           ^
UnusedMethodUtils.cpp:563:95: error: cast from ‘unsigned char*’ to ‘unsigned int’ loses precision [-fpermissive]
                 pUsage->pCalls[pUsage->nCurrCall].objaddress = (unsigned int)(pObject->pObject);
                                                                                               ^
UnusedMethodUtils.cpp: In function ‘void MarkCalls(MethodUsage*, ObjectEntry*)’:
UnusedMethodUtils.cpp:822:87: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
                 ObjectEntry* pSubObject = GetObject((unsigned char*)(pCall->objaddress));
                                                                                       ^
make[1]: *** [UnusedMethodUtils.o] Error 1
```

**Comment by reltham** [comment]
It compiles fine under gcc 4.6.2. Since when did they change it so that explicitly casting doesn't get rid of the "loses precision" thing? And when did that become an error instead of a warning?

**Comment by reltham** [comment]
I submitted a fixup for you that should work. I don't have gcc 4.8.3 available right now to test on, so if there were other problems besides what you listed then it'll have to wait.  It's annoying how they keep changing what is a warning or error and that even with an explicit cast they now don't shut up about lost precision and call it an error.

**Comment by drawkula** [comment]
Compiles on Debian8 (gcc version 4.9.2).
